// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNu9FxLcyjEv0fQT31n4xduX6ISUURLtk',
    appId: '1:610996788108:web:36d3ea5a79c5bcf29394a9',
    messagingSenderId: '610996788108',
    projectId: 'zoho-1a351',
    authDomain: 'zoho-1a351.firebaseapp.com',
    storageBucket: 'zoho-1a351.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFO1jmxKBHaD34cMIvH6XeFXYphbQ6u7Q',
    appId: '1:610996788108:android:509398482b0f59c49394a9',
    messagingSenderId: '610996788108',
    projectId: 'zoho-1a351',
    storageBucket: 'zoho-1a351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8fY6aP14CB17XcxKhFfLsx5eygrHOZIU',
    appId: '1:610996788108:ios:fac3910fb2dc8d3e9394a9',
    messagingSenderId: '610996788108',
    projectId: 'zoho-1a351',
    storageBucket: 'zoho-1a351.appspot.com',
    iosBundleId: 'com.example.ngoproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8fY6aP14CB17XcxKhFfLsx5eygrHOZIU',
    appId: '1:610996788108:ios:fac3910fb2dc8d3e9394a9',
    messagingSenderId: '610996788108',
    projectId: 'zoho-1a351',
    storageBucket: 'zoho-1a351.appspot.com',
    iosBundleId: 'com.example.ngoproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNu9FxLcyjEv0fQT31n4xduX6ISUURLtk',
    appId: '1:610996788108:web:f5542acbd39045199394a9',
    messagingSenderId: '610996788108',
    projectId: 'zoho-1a351',
    authDomain: 'zoho-1a351.firebaseapp.com',
    storageBucket: 'zoho-1a351.appspot.com',
  );
}
